### ISSUE TITLE
can't find the download link

### ISSUE THREAD

**Issue by evilmaran** [felipegiacomozzi/the-trove-downloader#1]
"Execute TheDroveDownloader.exe and follow the instructions."

can't find the exe anywhere.

**Comment by felipegiacomozzi** [comment]
> "Execute TheDroveDownloader.exe and follow the instructions."
> 
> can't find the exe anywhere.

Its in the releases page: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.0
I'm gonna link that on the readme too.

**Comment by evilmaran** [comment]
im blind, thanks.

**Comment by evilmaran** [comment]
i think i'm missing something, i follow the steps, and it closes, nothing happens after.

i input path to save files: E:\
then option 3 specific folder: https://thetrove.net/Books/Warhammer/
no ignored files
default concurrent downloads
then this list comes on real fast, and then it closes and nothing happens

**Comment by felipegiacomozzi** [comment]
> i think i'm missing something, i follow the steps, and it closes, nothing happens after.
> 
> i input path to save files: E:
> then option 3 specific folder: https://thetrove.net/Books/Warhammer/
> no ignored files
> default concurrent downloads
> then this list comes on real fast, and then it closes and nothing happens

On the specific folder try only Warhammer

**Comment by evilmaran** [comment]
still same thing, the list and the closing happens so fast i cant see what is happening, so not sure what it is doing those last few seconds or what is going wrong if something is, but my download location stays empty, i dont think a few 100gig gets downloaded in 2 seconds to somewhere on my system.

**Comment by felipegiacomozzi** [comment]
> still same thing, the list and the closing happens so fast i cant see what is happening, so not sure what it is doing those last few seconds or what is going wrong if something is, but my download location stays empty, i dont think a few 100gig gets downloaded in 2 seconds to somewhere on my system.

I released a new version fixing this bug,
could you try again?

**Comment by evilmaran** [comment]
ok downloaded new version.

using e: as download directory
trying to download folder warhammer

window closes nothing happens.

**Comment by evilmaran** [comment]
finally got a screenshot of what happens just before it closes: 
http://prntscr.com/tm3aji

**Comment by felipegiacomozzi** [comment]
> finally got a screenshot of what happens just before it closes:
> http://prntscr.com/tm3aji

You can run without it closing by calling the .exe inside a Command Prompt,
that way you can see the error msg

**Comment by evilmaran** [comment]
here we go: http://prntscr.com/tm9zoa
error message

**Comment by felipegiacomozzi** [comment]
> here we go: http://prntscr.com/tm9zoa
> error message

That`s the error I fixed.
Make sure you download and use this latest version https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.1

I just tested on the 1.0.1 and this problem is fixed

**Comment by evilmaran** [comment]
thanks a lot, it is downloading now
