### ISSUE TITLE
Download stopped after multiple failures

### ISSUE THREAD

**Issue by AetheriumAeon** [felipegiacomozzi/the-trove-downloader#10]
[Error-637337073146624431.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5112933/Error-637337073146624431.txt)

Error file included above. It seemed to keep failing to download a .zip file repeatedly before citing "multiple errors" as being the cause of canceling the task.

**Comment by felipegiacomozzi** [comment]
@AetheriumAeon is it always this zip file MapPack 01 - Abstract Texture Art Media Assets.zip?
This seems to be a connection problem
