### ISSUE TITLE
Looks like a new version of the site went up, having trouble downloading files now

### ISSUE THREAD

**Issue by Tarantula123** [felipegiacomozzi/the-trove-downloader#11]
Looks like the new site format doesnt agree with the downloader, may need to rewrite or possible just error on my end?

**Comment by felipegiacomozzi** [comment]
> Looks like the new site format doesnt agree with the downloader, may need to rewrite or possible just error on my end?

Yes, it need to be adapted for the new website

**Comment by derekleighstark** [comment]
Yep, came here to say the same thing, it didn't work for me with the new site. Hope it's still possible to use The Trove Downloader, its been a great piece of software so far!

**Comment by felipegiacomozzi** [comment]
Just released a new version adapting to the new website.
Please guys give it a try, if there is any issues let me know.
@derekleighstark @Tarantula123 
https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.7
