### ISSUE TITLE
V1.0.7 Error - "Error reading item:"

### ISSUE THREAD

**Issue by Meketh74** [felipegiacomozzi/the-trove-downloader#12]
Hi felipegiacomozzi,

thanks for updating the tool to the new website structure! 

I encountered the attached errors while running the tool (re-running stops the tool at the same points):
[Error-637367350706160511.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5286820/Error-637367350706160511.txt)
[Error-637367358032838204.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5286879/Error-637367358032838204.txt)
[Error-637367359419625407.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5286880/Error-637367359419625407.txt)
[Error-637367366857869111.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5286881/Error-637367366857869111.txt)

Thanks for looking into this.

Best
M.

**Comment by gozmoth** [comment]
Hello !

Got the same issue.
[Error-637370072819601754.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5301037/Error-637370072819601754.txt)

Thanks !

**Comment by felipegiacomozzi** [comment]
Hello,
I've just released a new version.
It won`t really solve the problem but I really improved the log system, it will help to find this problem.
https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.8

If you guys could download it and post here the new log error file. 
Thanks

**Comment by Meketh74** [comment]
Hi @felipegiacomozzi ,

thanks für releasing a new version.

It still quits with V1.0.8 at the same spot. Tool stops downloading and asks "Press any key" then closes. Unfortunately it does not create a log file at all. 

<img width="830" alt="error" src="https://user-images.githubusercontent.com/69805450/94991249-19b34b00-0582-11eb-9aec-4fd4d9116f95.PNG">


As mentioned in another issue post it seems to be connected to either long path/filenames or a deep folder structure. The files themselves are downloadable if you do it directly via the website. 

Happy to provide any further info that might help in debugging.

Best and thanks again for your dedication and effort
M.

**Comment by felipegiacomozzi** [comment]
I just released a new version: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.10

I found some weird spacer elements that would break the program.
Could you try it out? Thanks!
