### ISSUE TITLE
V1.0.9 - Not downloading at all 

### ISSUE THREAD

**Issue by Meketh74** [felipegiacomozzi/the-trove-downloader#15]
Hi @felipegiacomozzi ,

thanks for releasing V1.0.9. 

Problem with V1.0.9: 
- Unfortunately, V1.0.9 is not downloading files for me at all. 

Compared to V1.0.8 the new version seems to be able to read all directories and files. It does create the directory structure on my disk. The on screen dialog also states that it is downloading files, but actually no files are downloaded and the directory structure on my disk stays empty (0 bytes)

This is the log file:
[the-trove-downloader.log](https://github.com/felipegiacomozzi/the-trove-downloader/files/5517818/the-trove-downloader.log)

Could you please look into this. 

Thanks and best
M.

**Comment by felipegiacomozzi** [comment]
Sorry @Meketh74, that was my bad.
To speed up my tests I commented the download section, that's why it wasn`t downloading.
This was really dumb, my bad.
Here is a release fixing this: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.10

**Comment by Meketh74** [comment]
@felipegiacomozzi 
Thanks a lot for fixing this so fast and definitely no need to apologize.
It is downloading now, only issue I have is that the overall download speed seems to be way slower than what would be expected.
I am on a 1gbit/s line and downloading a 30mb file is taking about 3 minutes. But this might also be a temporary server side issue. I will keep you posted.
Best
M.
