### ISSUE TITLE
Heres an interesting one: Trove Directory actually goes to a website

### ISSUE THREAD

**Issue by turnerjoy** [felipegiacomozzi/the-trove-downloader#17]
Not sure how you would handle this one 

In the folder

https://thetrove.is/Assets/By%20Artist%20or%20Source/0-hr/

The SF/ "folder"

https://thetrove.is/Assets/By%20Artist%20or%20Source/0-hr/SF/

Is actually a "website" of its own

**Comment by felipegiacomozzi** [comment]
Hello @turnerjoy,
unfortunately there is no way to handle this.
We can list all these websites and add to the ignore folder, so the downloads won't stop
