### ISSUE TITLE
V.1.0.12 - Issue with colon character (:) in thetrove.is folder name

### ISSUE THREAD

**Issue by Meketh74** [felipegiacomozzi/the-trove-downloader#18]
Hi @felipegiacomozzi 

first of all thanks a lot for the recent patches. V1.0.12 is running really well now and is working most of the time! Awesome job!

One error I have encountered is that the program stops when it tries to download from a folder with a colon (:) in it, as it is not able to create that folder in a windows environment (Error message: The directory name is invalid.)

An example for such a folder structure on trove.is is e.g.: Home/Books/World of Darkness (WoD) [multi]/LANG/ES/Hombre lobo: el apocalipsis.

See attached log for details:
[the-trove-downloader.log](https://github.com/felipegiacomozzi/the-trove-downloader/files/5590357/the-trove-downloader.log)

Is there a fix for this? 

Best and stay healthy
M.

**Comment by felipegiacomozzi** [comment]
Hello @Meketh74 ,

Just released a new version fixing that.
Could you try it out?

https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.13

Thanks 👍
