### ISSUE TITLE
Downloading Specific Sub-Folder

### ISSUE THREAD

**Issue by Christian-Dharma** [felipegiacomozzi/the-trove-downloader#2]
Having trouble trying to specify any folders that are more than 1 level deep. 

e.g. 
Dungeons & Dragons works OK
Dungeons & Dragons\5th Edition (5e)\3rd Party fails
Dungeons%20&%20Dragons/5th%20Edition%20(5e)/3rd%20Party fails

Is this possible?

**Comment by felipegiacomozzi** [comment]
> Having trouble trying to specify any folders that are more than 1 level deep.
> 
> e.g.
> Dungeons & Dragons works OK
> Dungeons & Dragons\5th Edition (5e)\3rd Party fails
> Dungeons%20&%20Dragons/5th%20Edition%20(5e)/3rd%20Party fails
> 
> Is this possible?

Unfortunately it is only implemented for first level
