### ISSUE TITLE
App failing on retries on 0 Byte files

### ISSUE THREAD

**Issue by GravGunner** [felipegiacomozzi/the-trove-downloader#4]
As the title says.
The App errors out on 0 Byte files(like empty text files in the folder, or non-existing references to other files).

The manual fix is to either delete(not recommended if you most likely have to retry a few times) or make/fill a file yourself that is at least 1 kb(app skips it as it should next time around)

Version: Win-x64 v1.0.1

**Comment by felipegiacomozzi** [comment]
Hello,

Could you try changing the line 163 from:
`using (var fs = new FileStream(path, FileMode.CreateNew)) {`
to:
`using (var fs = new FileStream(path, FileMode.OpenOrCreate, FileAccess.ReadWrite)) {`
Maybe this will solve the retry, reopening the file and writing on top of it.

**Comment by felipegiacomozzi** [comment]
@GravGunner just released a new version fixing this error.

Could you try it (https://github.com/felipegiacomozzi/the-trove-downloader/releases)?

Thank you.
