### ISSUE TITLE
TheTroveDownloader quits without warning  durring download

### ISSUE THREAD

**Issue by mrbuzzsaw** [felipegiacomozzi/the-trove-downloader#5]
i  have tried several times to pull and it quits without warning  can you assist me ion resolving this?

**Comment by felipegiacomozzi** [comment]
Sure, 
Can you run it inside a Command Prompt?
That way the window won't close and we see the error.
Can you also post it here the inputs that you typed?
Thanks.

**Comment by felipegiacomozzi** [comment]
@mrbuzzsaw I just released a new version that won't quit after is finished and if an error occurs, it will create a file with details about the error.

https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.3

Could you try this new version?
If the problem still occurs, could you post the error file here?

Thank you.

**Comment by mrbuzzsaw** [comment]
[Error-637326665843602165.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5053534/Error-637326665843602165.txt)

**Comment by mrbuzzsaw** [comment]
that is the error i hope it helps

**Comment by felipegiacomozzi** [comment]
@mrbuzzsaw that error log helped a lot, thanks!

Just released a new version fixing this error.

Could you try it (https://github.com/felipegiacomozzi/the-trove-downloader/releases)?

**Comment by mrbuzzsaw** [comment]
wow still working ill update if it quits but so far so good!!!

**Comment by mrbuzzsaw** [comment]
[Error-637326889115241050.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5054626/Error-637326889115241050.txt)

**Comment by mrbuzzsaw** [comment]
well it ran a long  time but errored again

**Comment by felipegiacomozzi** [comment]
@mrbuzzsaw it seems a specific link on the website is causing this.

I added more log information on the item being downloaded that caused the error.
Could you download the new version and upload here the error file?
https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.5

Thanks.

**Comment by mrbuzzsaw** [comment]
[Error-637327512910648663.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5059732/Error-637327512910648663.txt)

**Comment by felipegiacomozzi** [comment]
> [Error-637327512910648663.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5059732/Error-637327512910648663.txt)

I don't know why, but this release version was still at 1.0.4. I just re-uploaded the 1.0.5
Could you download it again and send the new error?
Sorry for that

**Comment by mrbuzzsaw** [comment]
sure ill try again 
[Error-637327629080324642.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5060014/Error-637327629080324642.txt)

**Comment by mrbuzzsaw** [comment]
that one did not take long to crash

**Comment by felipegiacomozzi** [comment]
> that one did not take long to crash

Yep, it had a network connection.
Probably the website was unavailable for a moment.

Could you run it again?

**Comment by mrbuzzsaw** [comment]
ok ran it several times it kicked out error codes but finally appears to have completed

**Comment by mrbuzzsaw** [comment]
[Error-637328814455846241.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5071717/Error-637328814455846241.txt)

**Comment by Aerospacesmith** [comment]
I haven't dived into much of the code yet, but it looks like the error is caused when downloading large files. When I download with 10 threads, it errors out on files that are larger than about 200 MB in size. When I reduce it to 5 threads, it can download about 400MB files without error, but it still errors on larger files. I'm not sure how yet, but can the download buffer size be increased?

**Comment by felipegiacomozzi** [comment]
@Aerospacesmith I just released a new version fixing this size limit bug.

https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.6
