### ISSUE TITLE
Error with buffer size / large files > 2.1GB

### ISSUE THREAD

**Issue by Meketh74** [felipegiacomozzi/the-trove-downloader#6]
Hi felipegiacomozzi,

super awesome project. Thanks a lot for this!

I have encountered a problem with a large file (4GB). See attached error.txt:

[Error-637332785761840224.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5084884/Error-637332785761840224.txt)

Woudl it also be possible to have a continue after an error/not downloaded file e.g. like skipping the file that cannot be downloaded, writign the file name to a text file and continuing with the next file? 

Best
meketh74

**Comment by PrometeusGod** [comment]
[Error-637333147438495617.txt](https://github.com/felipegiacomozzi/the-trove-downloader/files/5087674/Error-637333147438495617.txt)
Same

**Comment by felipegiacomozzi** [comment]
@Meketh74  @PrometeusGod  
Just released a new version fixing this bug, could you guys try it out?

https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.6

**Comment by Meketh74** [comment]
@felipegiacomozzi: Thank you. The new version fixed the large file issue as far as I can tell.
Best and stay healthy
Meketh74
